; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CTools"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Comottec Tecnologia da Informa��o EIRELI"
#define MyAppURL "https://www.comottec.com.br/ctools"
#define MyAppExeName "CTools.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{24531FCE-FB44-46C6-9B8F-34BF5322CDCF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userpf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=Z:\git\ctools\LICENSE
; Remove the following line to run in administrative install mode (install for all users.)
;PrivilegesRequired=lowest
OutputDir=Z:\git\ctools\distr\buildSetup
OutputBaseFilename=setup
SetupIconFile=Z:\git\ctools\distr\ctools.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ChangesEnvironment=yes

[CustomMessages]
AppAddPath=Adicionar a pasta do aplicativo ao path do sistema

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"

[Tasks]
;Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: modifypath; Description:{cm:AppAddPath};   

[Files]
Source: "Z:\git\ctools\build\CTools.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\git\ctools\batches\CTools-list.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\git\ctools\batches\CTools-start.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\git\ctools\batches\CTools-stop.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\git\ctools\batches\CTools-update.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\git\ctools\batches\CTools-config.bat"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\CTools\{#MyAppName} list"; Filename: "{app}\CTools-list.bat"
Name: "{autoprograms}\CTools\{#MyAppName} start"; Filename: "{app}\CTools-start.bat"; \
  AfterInstall: SetElevationBit('{autoprograms}\CTools\{#MyAppName} start.lnk')
Name: "{autoprograms}\CTools\{#MyAppName} stop"; Filename: "{app}\CTools-stop.bat"; \
  AfterInstall: SetElevationBit('{autoprograms}\CTools\{#MyAppName} stop.lnk')
Name: "{autoprograms}\CTools\{#MyAppName} update"; Filename: "{app}\CTools-update.bat"

[Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]


procedure SetElevationBit(Filename: string);
var
  Buffer: string;
  Stream: TStream;
begin
  Filename := ExpandConstant(Filename);
  Log('Setting elevation bit for ' + Filename);

  Stream := TFileStream.Create(FileName, fmOpenReadWrite);
  try
    Stream.Seek(21, soFromBeginning);
    SetLength(Buffer, 1);
    Stream.ReadBuffer(Buffer, 1);
    Buffer[1] := Chr(Ord(Buffer[1]) or $20);
    Stream.Seek(-1, soFromCurrent);
    Stream.WriteBuffer(Buffer, 1);
  finally
    Stream.Free;
  end;
end;

const
  ModPathName = 'modifypath';
  ModPathType = 'user';

function ModPathDir(): TArrayOfString;
begin
  setArrayLength(Result, 1);
  Result[0] := ExpandConstant('{app}');
end;
#include "modpath.iss"


